const portfolioData = [
    {
        id: 1,
        title: "产品KV",
        category: "视觉设计 / Visual Design",
        cover: "https://placehold.co/600x800/0000ff/0000ff",
        date: "2025.10",
        description: "高品质产品主视觉设计，通过极简的几何构图突出核心卖点。",
        concept: "包豪斯主义构图，利用强烈的明暗对比和线性排版，引导用户视觉焦点。",
        images: [
            "images/kv/kv (1).jpg",
            "images/kv/kv (2).jpg",
            "images/kv/kv (3).jpg",
            "images/kv/kv (4).jpg",
            "images/kv/kv (5).jpg",
            "images/kv/kv (6).jpg",
            "images/kv/kv (7).jpg",
            "images/kv/kv (8).jpg",
            "images/kv/kv (9).jpg",
            "images/kv/kv (10).jpg",
            "images/kv/kv (11).jpg",
            "images/kv/kv (12).jpg",
            "images/kv/kv (13).jpg",
            "images/kv/kv (14).jpg",
            "images/kv/kv (15).jpg",
            "images/kv/kv (16).jpg",
            "images/kv/kv (17).jpg",
            "images/kv/kv (18).jpg",
            "images/kv/kv (19).jpg",
            "images/kv/kv (20).jpg",
            "images/kv/kv (21).jpg",
            "images/kv/kv (22).jpg",
            "images/kv/kv (23).jpg",
            "images/kv/kv (24).jpg",
            "images/kv/kv (25).jpg",
            "images/kv/kv (26).jpg",
            "images/kv/kv (27).jpg",
            "images/kv/kv (28).jpg",
            "images/kv/kv (29).jpg",
            "images/kv/kv (30).jpg",
            "images/kv/kv (31).jpg",
            "images/kv/kv (32).jpg",
            "images/kv/kv (33).jpg",
            "images/kv/kv (34).jpg",
            "images/kv/kv (35).jpg",
            "images/kv/kv (36).jpg",
            "images/kv/kv (37).jpg",
            "images/kv/kv (38).jpg",
            "images/kv/kv (39).jpg",
            "images/kv/kv (40).jpg",
            "images/kv/kv (41).jpg",
            "images/kv/kv (42).jpg",
            "images/kv/kv (43).jpg",
            "images/kv/kv (44).jpg",
            "images/kv/kv (45).jpg",
            "images/kv/kv (46).jpg",
            "images/kv/kv (47).jpg",
            "images/kv/kv (48).jpg",
            "images/kv/kv (49).jpg",
            "images/kv/kv (50).jpg",
            "images/kv/kv (51).jpg",
            "images/kv/kv (52).jpg",
            "images/kv/kv (53).jpg",
            "images/kv/kv (54).jpg",
            "images/kv/kv (55).jpg",
            "images/kv/kv (56).jpg",
            "images/kv/kv (57).jpg",
            "images/kv/kv (58).jpg",
            "images/kv/kv (59).jpg",
            "images/kv/kv (60).jpg",
            "images/kv/kv (61).jpg",
            "images/kv/kv (62).jpg",
            "images/kv/kv (63).jpg",
            "images/kv/kv (64).jpg",
            "images/kv/kv (65).jpg",
            "images/kv/kv (66).jpg",
            "images/kv/kv (67).jpg",
            "images/kv/kv (68).jpg",
            "images/kv/kv (69).jpg",
            "images/kv/kv (70).jpg",
            "images/kv/kv (71).jpg",
            "images/kv/kv (72).jpg",
            "images/kv/kv (73).jpg"
        ]
    },
    {
        id: 6,
        title: "动态视频",
        category: "动态图形 / Motion Graphics",
        cover: "https://placehold.co/600x800/ffffff/ffffff",
        date: "2024.10",
        description: "富有节奏感的动态视觉呈现，将平面构图与时间维度深度结合。",
        concept: "流动的包豪斯，通过关键帧的精确控制，展现几何元素的韵律之美。",
        images: [
            "images/motion/1.mp4",
            "images/motion/2.mp4",
            "images/motion/3.mp4",
            "images/motion/4.mp4",
            "images/motion/5.mp4",
            "images/motion/6.mp4",
            "images/motion/7.mp4",
            "images/motion/8.mp4",
            "images/motion/9.mp4",
            "images/motion/10.mp4",
            "images/motion/11.mp4",
            "images/motion/12.mp4",
            "images/motion/gif (1).GIF",
            "images/motion/gif (2).GIF",
            "images/motion/gif (3).GIF"
        ]
    },
    {
        id: 4,
        title: "AIGC",
        coverTitle: "聚焦AI",
        category: "实时跟随 / AI Technology",
        cover: "https://placehold.co/600x800/0000ff/0000ff",
        date: "2025.02",
        description: "利用 AI 生成技术探索视觉边界，将算法逻辑转化为包豪斯式的纯粹美感。",
        concept: "算法与美学的交汇，通过人工干预使 AI 产出具备严谨的几何秩序。",
        images: [
            "images/aigc/ai (1).png",
            "images/aigc/ai (2).png",
            "images/aigc/ai (3).png",
            "images/aigc/ai (4).png",
            "images/aigc/ai (5).png",
            "images/aigc/ai (6).png",
            "images/aigc/ai (7).png",
            "images/aigc/ai (8).png",
            "images/aigc/ai (9).png",
            "images/aigc/ai (10).png",
            "images/aigc/ai (11).png",
            "images/aigc/ai (12).png",
            "images/aigc/ai (13).png",
            "images/aigc/ai (14).png",
            "images/aigc/ai (15).png",
            "images/aigc/ai (16).png",
            "images/aigc/ai (17).png",
            "images/aigc/ai (18).png",
            "images/aigc/ai (19).png",
            "images/aigc/ai (20).png",
            "images/aigc/ai (21).png",
            "images/aigc/ai (22).png",
            "images/aigc/ai (23).png",
            "images/aigc/ai (24).png",
            "images/aigc/ai (25).png",
            "images/aigc/ai (26).png",
            "images/aigc/ai (27).png",
            "images/aigc/ai (28).png",
            "images/aigc/ai (29).png",
            "images/aigc/ai (30).png",
            "images/aigc/ai (31).png",
            "images/aigc/ai (32).png",
            "images/aigc/ai (33).png"
        ]
    },
    {
        id: 5,
        title: "产品建模",
        category: "3D建模 / 3D Modeling",
        cover: "images/3d/1-大华2.jpg",
        date: "2024.12",
        description: "高精度 3D 产品建模，还原工业设计的材质质感与纯粹结构。",
        concept: "在三维空间中重塑几何基本型，探索光影在纯净表面的自然流动。",
        images: [
            "images/3d/1-大华1.jpg",
            "images/3d/1-大华2.jpg",
            "images/3d/2-年货1.jpg",
            "images/3d/2-年货2.jpg",
            "images/3d/3-康王1.jpg",
            "images/3d/3-康王2.jpg",
            "images/3d/4-场景1.jpg",
            "images/3d/4-场景2.jpg",
            "images/3d/5-蛇年1.jpg",
            "images/3d/5-蛇年2.jpg",
            "images/3d/6-场景1.jpg",
            "images/3d/6-场景2.jpg",
            "images/3d/7-场景1.jpg",
            "images/3d/7-场景2.jpg",
            "images/3d/8-达喜1.jpg",
            "images/3d/8-达喜2.jpg",
            "images/3d/9-场景1.jpg",
            "images/3d/9-场景2.jpg",
            "images/3d/10-场景1.jpg",
            "images/3d/10-场景2.jpg",
            "images/3d/11-场景1.jpg",
            "images/3d/11-场景2.jpg",
            "images/3d/12-场景1.jpg",
            "images/3d/12-场景2.jpg",
            "images/3d/13-场景1.jpg",
            "images/3d/13-场景2.jpg",
            "images/3d/14-场景1.jpg",
            "images/3d/14-场景2.jpg",
            "images/3d/15-特伦随1.jpg",
            "images/3d/15-特伦随2.jpg",
            "images/3d/16-蒙牛1.jpg",
            "images/3d/16-蒙牛2.jpg",
            "images/3d/17-蒙牛六一八1.jpg",
            "images/3d/17-蒙牛六一八2.jpg",
            "images/3d/18-蒙蒙1.jpg",
            "images/3d/18-蒙蒙2.jpg",
            "images/3d/19-牛气1.jpg",
            "images/3d/19-牛气2.jpg",
            "images/3d/20-五丰1.jpg",
            "images/3d/20-五丰2.jpg"
        ]
    },
    {
        id: 2,
        title: "产品详情",
        category: "交互设计 / Interaction Design",
        cover: "https://placehold.co/600x800/0000ff/0000ff",
        date: "2025.08",
        description: "深度的产品细节展示，结合信息图表和极简排版，清晰传达产品参数。",
        concept: "形式追随功能。每一个视觉元素都是为了更高效的信息传递。",
        images: [
            "images/detail/detail (1).jpg",
            "images/detail/detail (2).jpg",
            "images/detail/detail (3).jpg",
            "images/detail/detail (4).jpg",
            "images/detail/detail (5).jpg",
            "images/detail/detail (6).jpg",
            "images/detail/detail (7).jpg",
            "images/detail/detail (8).jpg",
            "images/detail/detail (9).jpg",
            "images/detail/detail (10).jpg",
            "images/detail/detail (11).jpg",
            "images/detail/detail (12).jpg",
            "images/detail/detail (13).jpg",
            "images/detail/detail (14).jpg",
            "images/detail/detail (15).jpg",
            "images/detail/detail (16).jpg",
            "images/detail/detail (17).jpg",
            "images/detail/detail (18).jpg",
            "images/detail/detail (19).jpg",
            "images/detail/detail (20).jpg",
            "images/detail/detail (21).jpg",
            "images/detail/detail (22).jpg",
            "images/detail/detail (23).jpg",
            "images/detail/detail (24).jpg",
            "images/detail/detail (25).jpg",
            "images/detail/detail (26).jpg",
            "images/detail/detail (27).jpg",
            "images/detail/detail (28).jpg",
            "images/detail/detail (29).jpg",
            "images/detail/detail (30).jpg",
            "images/detail/detail (31).jpg",
            "images/detail/detail (32).jpg",
            "images/detail/detail (33).jpg",
            "images/detail/detail (34).jpg",
            "images/detail/detail (35).jpg",
            "images/detail/detail (36).jpg",
            "images/detail/detail (37).jpg",
            "images/detail/detail (38).jpg",
            "images/detail/detail (39).jpg",
            "images/detail/detail (40).jpg",
            "images/detail/detail (41).jpg",
            "images/detail/detail (42).jpg",
            "images/detail/detail (43).jpg",
            "images/detail/detail (44).jpg",
            "images/detail/detail (45).jpg",
            "images/detail/detail (46).jpg",
            "images/detail/detail (47).jpg",
            "images/detail/detail (48).jpg",
            "images/detail/detail (49).jpg",
            "images/detail/detail (50).jpg",
            "images/detail/detail (51).jpg",
            "images/detail/detail (52).jpg",
            "images/detail/detail (53).jpg",
            "images/detail/detail (54).jpg",
            "images/detail/detail (55).jpg",
            "images/detail/detail (56).jpg",
            "images/detail/detail (57).jpg",
            "images/detail/detail (58).jpg",
            "images/detail/detail (59).jpg",
            "images/detail/detail (60).jpg",
            "images/detail/detail (61).jpg",
            "images/detail/detail (62).jpg",
            "images/detail/detail (63).jpg",
            "images/detail/detail (64).jpg",
            "images/detail/detail (65).jpg",
            "images/detail/detail (66).jpg",
            "images/detail/detail (67).jpg",
            "images/detail/detail (68).jpg",
            "images/detail/detail (69).jpg",
            "images/detail/detail (70).jpg",
            "images/detail/detail (71).jpg",
            "images/detail/detail (72).jpg",
            "images/detail/detail (73).jpg",
            "images/detail/detail (74).jpg",
            "images/detail/detail (75).jpg",
            "images/detail/detail (76).jpg",
            "images/detail/detail (77).jpg",
            "images/detail/detail (78).jpg",
            "images/detail/detail (79).jpg",
            "images/detail/detail (80).jpg"
        ]
    },
    {
        id: 3,
        title: "首页模块",
        category: "网页设计 / Web Design",
        cover: "https://placehold.co/600x800/ffffff/ffffff",
        date: "2025.05",
        description: "全站式极简网页布局，采用规整的网格系统，提供流畅的响应式体验。",
        concept: "现代包豪斯数字实践，打破传统束缚，追求空间与节奏的完美平衡。",
        images: [
            "images/web/web (1).jpg",
            "images/web/web (2).jpg",
            "images/web/web (3).jpg",
            "images/web/web (4).jpg",
            "images/web/web (5).jpg",
            "images/web/web (6).jpg",
            "images/web/web (7).jpg",
            "images/web/web (8).jpg",
            "images/web/web (9).jpg",
            "images/web/web (10).jpg",
            "images/web/web (11).jpg",
            "images/web/web (12).jpg",
            "images/web/web (13).jpg",
            "images/web/web (14).jpg",
            "images/web/web (15).jpg",
            "images/web/web (16).jpg",
            "images/web/web (17).jpg",
            "images/web/web (18).jpg",
            "images/web/web (19).jpg",
            "images/web/web (20).jpg",
            "images/web/web (21).jpg",
            "images/web/web (22).jpg",
            "images/web/web (23).jpg",
            "images/web/web (24).jpg",
            "images/web/web (25).jpg",
            "images/web/web (26).jpg",
            "images/web/web (27).jpg",
            "images/web/web (28).jpg",
            "images/web/web (29).jpg",
            "images/web/web (30).jpg",
            "images/web/web (31).jpg",
            "images/web/web (32).jpg",
            "images/web/web (33).jpg",
            "images/web/web (34).jpg",
            "images/web/web (35).jpg",
            "images/web/web (36).jpg",
            "images/web/web (37).jpg",
            "images/web/web (38).jpg",
            "images/web/web (39).jpg",
            "images/web/web (40).jpg",
            "images/web/web (41).jpg",
            "images/web/web (42).jpg",
            "images/web/web (43).jpg",
            "images/web/web (44).jpg",
            "images/web/web (45).jpg",
            "images/web/web (46).jpg",
            "images/web/web (47).jpg",
            "images/web/web (48).jpg",
            "images/web/web (49).jpg",
            "images/web/web (50).jpg",
            "images/web/web (51).jpg",
            "images/web/web (52).jpg",
            "images/web/web (53).jpg",
            "images/web/web (54).jpg",
            "images/web/web (55).jpg",
            "images/web/web (56).jpg"
        ]
    },
    {
        id: 999,
        title: "全部作品",
        category: "作品集总览 / All Works",
        cover: "", // Not used
        date: "2024-2025",
        description: "这里汇集了所有的设计探索与实践成果。",
        concept: "从平面到动态，从二维到三维，全方位的视觉呈现。",
        images: [
            "images/kv/kv (1).jpg",
            "images/kv/kv (2).jpg",
            "images/kv/kv (3).jpg",
            "images/kv/kv (4).jpg",
            "images/kv/kv (5).jpg",
            "images/kv/kv (6).jpg",
            "images/kv/kv (7).jpg",
            "images/kv/kv (8).jpg",
            "images/kv/kv (9).jpg",
            "images/kv/kv (10).jpg",
            "images/kv/kv (11).jpg",
            "images/kv/kv (12).jpg",
            "images/kv/kv (13).jpg",
            "images/kv/kv (14).jpg",
            "images/kv/kv (15).jpg",
            "images/kv/kv (16).jpg",
            "images/kv/kv (17).jpg",
            "images/kv/kv (18).jpg",
            "images/kv/kv (19).jpg",
            "images/kv/kv (20).jpg",
            "images/kv/kv (21).jpg",
            "images/kv/kv (22).jpg",
            "images/kv/kv (23).jpg",
            "images/kv/kv (24).jpg",
            "images/kv/kv (25).jpg",
            "images/kv/kv (26).jpg",
            "images/kv/kv (27).jpg",
            "images/kv/kv (28).jpg",
            "images/kv/kv (29).jpg",
            "images/kv/kv (30).jpg",
            "images/kv/kv (31).jpg",
            "images/kv/kv (32).jpg",
            "images/kv/kv (33).jpg",
            "images/kv/kv (34).jpg",
            "images/kv/kv (35).jpg",
            "images/kv/kv (36).jpg",
            "images/kv/kv (37).jpg",
            "images/kv/kv (38).jpg",
            "images/kv/kv (39).jpg",
            "images/kv/kv (40).jpg",
            "images/kv/kv (41).jpg",
            "images/kv/kv (42).jpg",
            "images/kv/kv (43).jpg",
            "images/kv/kv (44).jpg",
            "images/kv/kv (45).jpg",
            "images/kv/kv (46).jpg",
            "images/kv/kv (47).jpg",
            "images/kv/kv (48).jpg",
            "images/kv/kv (49).jpg",
            "images/kv/kv (50).jpg",
            "images/kv/kv (51).jpg",
            "images/kv/kv (52).jpg",
            "images/kv/kv (53).jpg",
            "images/kv/kv (54).jpg",
            "images/kv/kv (55).jpg",
            "images/kv/kv (56).jpg",
            "images/kv/kv (57).jpg",
            "images/kv/kv (58).jpg",
            "images/kv/kv (59).jpg",
            "images/kv/kv (60).jpg",
            "images/kv/kv (61).jpg",
            "images/kv/kv (62).jpg",
            "images/kv/kv (63).jpg",
            "images/kv/kv (64).jpg",
            "images/kv/kv (65).jpg",
            "images/kv/kv (66).jpg",
            "images/kv/kv (67).jpg",
            "images/kv/kv (68).jpg",
            "images/kv/kv (69).jpg",
            "images/kv/kv (70).jpg",
            "images/kv/kv (71).jpg",
            "images/kv/kv (72).jpg",
            "images/kv/kv (73).jpg",
            "images/motion/1.mp4",
            "images/motion/2.mp4",
            "images/motion/3.mp4",
            "images/motion/4.mp4",
            "images/motion/5.mp4",
            "images/motion/6.mp4",
            "images/motion/7.mp4",
            "images/motion/8.mp4",
            "images/motion/9.mp4",
            "images/motion/10.mp4",
            "images/motion/11.mp4",
            "images/motion/12.mp4",
            "images/motion/gif (1).GIF",
            "images/motion/gif (2).GIF",
            "images/motion/gif (3).GIF",
            "images/aigc/ai (1).png",
            "images/aigc/ai (2).png",
            "images/aigc/ai (3).png",
            "images/aigc/ai (4).png",
            "images/aigc/ai (5).png",
            "images/aigc/ai (6).png",
            "images/aigc/ai (7).png",
            "images/aigc/ai (8).png",
            "images/aigc/ai (9).png",
            "images/aigc/ai (10).png",
            "images/aigc/ai (11).png",
            "images/aigc/ai (12).png",
            "images/aigc/ai (13).png",
            "images/aigc/ai (14).png",
            "images/aigc/ai (15).png",
            "images/aigc/ai (16).png",
            "images/aigc/ai (17).png",
            "images/aigc/ai (18).png",
            "images/aigc/ai (19).png",
            "images/aigc/ai (20).png",
            "images/aigc/ai (21).png",
            "images/aigc/ai (22).png",
            "images/aigc/ai (23).png",
            "images/aigc/ai (24).png",
            "images/aigc/ai (25).png",
            "images/aigc/ai (26).png",
            "images/aigc/ai (27).png",
            "images/aigc/ai (28).png",
            "images/aigc/ai (29).png",
            "images/aigc/ai (30).png",
            "images/aigc/ai (31).png",
            "images/aigc/ai (32).png",
            "images/aigc/ai (33).png",
            "images/web/web (1).jpg",
            "images/web/web (2).jpg",
            "images/web/web (3).jpg",
            "images/web/web (4).jpg",
            "images/web/web (5).jpg",
            "images/web/web (6).jpg",
            "images/web/web (7).jpg",
            "images/web/web (8).jpg",
            "images/web/web (9).jpg",
            "images/web/web (10).jpg",
            "images/web/web (11).jpg",
            "images/web/web (12).jpg",
            "images/web/web (13).jpg",
            "images/web/web (14).jpg",
            "images/web/web (15).jpg",
            "images/web/web (16).jpg",
            "images/web/web (17).jpg",
            "images/web/web (18).jpg",
            "images/web/web (19).jpg",
            "images/web/web (20).jpg",
            "images/web/web (21).jpg",
            "images/web/web (22).jpg",
            "images/web/web (23).jpg",
            "images/web/web (24).jpg",
            "images/web/web (25).jpg",
            "images/web/web (26).jpg",
            "images/web/web (27).jpg",
            "images/web/web (28).jpg",
            "images/web/web (29).jpg",
            "images/web/web (30).jpg",
            "images/web/web (31).jpg",
            "images/web/web (32).jpg",
            "images/web/web (33).jpg",
            "images/web/web (34).jpg",
            "images/web/web (35).jpg",
            "images/web/web (36).jpg",
            "images/web/web (37).jpg",
            "images/web/web (38).jpg",
            "images/web/web (39).jpg",
            "images/web/web (40).jpg",
            "images/web/web (41).jpg",
            "images/web/web (42).jpg",
            "images/web/web (43).jpg",
            "images/web/web (44).jpg",
            "images/web/web (45).jpg",
            "images/web/web (46).jpg",
            "images/web/web (47).jpg",
            "images/web/web (48).jpg",
            "images/web/web (49).jpg",
            "images/web/web (50).jpg",
            "images/web/web (51).jpg",
            "images/web/web (52).jpg",
            "images/web/web (53).jpg",
            "images/web/web (54).jpg",
            "images/web/web (55).jpg",
            "images/web/web (56).jpg",
            "images/detail/detail (1).jpg",
            "images/detail/detail (2).jpg",
            "images/detail/detail (3).jpg",
            "images/detail/detail (4).jpg",
            "images/detail/detail (5).jpg",
            "images/detail/detail (6).jpg",
            "images/detail/detail (7).jpg",
            "images/detail/detail (8).jpg",
            "images/detail/detail (9).jpg",
            "images/detail/detail (10).jpg",
            "images/detail/detail (11).jpg",
            "images/detail/detail (12).jpg",
            "images/detail/detail (13).jpg",
            "images/detail/detail (14).jpg",
            "images/detail/detail (15).jpg",
            "images/detail/detail (16).jpg",
            "images/detail/detail (17).jpg",
            "images/detail/detail (18).jpg",
            "images/detail/detail (19).jpg",
            "images/detail/detail (20).jpg",
            "images/detail/detail (21).jpg",
            "images/detail/detail (22).jpg",
            "images/detail/detail (23).jpg",
            "images/detail/detail (24).jpg",
            "images/detail/detail (25).jpg",
            "images/detail/detail (26).jpg",
            "images/detail/detail (27).jpg",
            "images/detail/detail (28).jpg",
            "images/detail/detail (29).jpg",
            "images/detail/detail (30).jpg",
            "images/detail/detail (31).jpg",
            "images/detail/detail (32).jpg",
            "images/detail/detail (33).jpg",
            "images/detail/detail (34).jpg",
            "images/detail/detail (35).jpg",
            "images/detail/detail (36).jpg",
            "images/detail/detail (37).jpg",
            "images/detail/detail (38).jpg",
            "images/detail/detail (39).jpg",
            "images/detail/detail (40).jpg",
            "images/detail/detail (41).jpg",
            "images/detail/detail (42).jpg",
            "images/detail/detail (43).jpg",
            "images/detail/detail (44).jpg",
            "images/detail/detail (45).jpg",
            "images/detail/detail (46).jpg",
            "images/detail/detail (47).jpg",
            "images/detail/detail (48).jpg",
            "images/detail/detail (49).jpg",
            "images/detail/detail (50).jpg",
            "images/detail/detail (51).jpg",
            "images/detail/detail (52).jpg",
            "images/detail/detail (53).jpg",
            "images/detail/detail (54).jpg",
            "images/detail/detail (55).jpg",
            "images/detail/detail (56).jpg",
            "images/detail/detail (57).jpg",
            "images/detail/detail (58).jpg",
            "images/detail/detail (59).jpg",
            "images/detail/detail (60).jpg",
            "images/detail/detail (61).jpg",
            "images/detail/detail (62).jpg",
            "images/detail/detail (63).jpg",
            "images/detail/detail (64).jpg",
            "images/detail/detail (65).jpg",
            "images/detail/detail (66).jpg",
            "images/detail/detail (67).jpg",
            "images/detail/detail (68).jpg",
            "images/detail/detail (69).jpg",
            "images/detail/detail (70).jpg",
            "images/detail/detail (71).jpg",
            "images/detail/detail (72).jpg",
            "images/detail/detail (73).jpg",
            "images/detail/detail (74).jpg",
            "images/detail/detail (75).jpg",
            "images/detail/detail (76).jpg",
            "images/detail/detail (77).jpg",
            "images/detail/detail (78).jpg",
            "images/detail/detail (79).jpg",
            "images/detail/detail (80).jpg",
            "images/3d/1-大华1.jpg",
            "images/3d/1-大华2.jpg",
            "images/3d/2-年货1.jpg",
            "images/3d/2-年货2.jpg",
            "images/3d/3-康王1.jpg",
            "images/3d/3-康王2.jpg",
            "images/3d/4-场景1.jpg",
            "images/3d/4-场景2.jpg",
            "images/3d/5-蛇年1.jpg",
            "images/3d/5-蛇年2.jpg",
            "images/3d/6-场景1.jpg",
            "images/3d/6-场景2.jpg",
            "images/3d/7-场景1.jpg",
            "images/3d/7-场景2.jpg",
            "images/3d/8-达喜1.jpg",
            "images/3d/8-达喜2.jpg",
            "images/3d/9-场景1.jpg",
            "images/3d/9-场景2.jpg",
            "images/3d/10-场景1.jpg",
            "images/3d/10-场景2.jpg",
            "images/3d/11-场景1.jpg",
            "images/3d/11-场景2.jpg",
            "images/3d/12-场景1.jpg",
            "images/3d/12-场景2.jpg",
            "images/3d/13-场景1.jpg",
            "images/3d/13-场景2.jpg",
            "images/3d/14-场景1.jpg",
            "images/3d/14-场景2.jpg",
            "images/3d/15-特伦随1.jpg",
            "images/3d/15-特伦随2.jpg",
            "images/3d/16-蒙牛1.jpg",
            "images/3d/16-蒙牛2.jpg",
            "images/3d/17-蒙牛六一八1.jpg",
            "images/3d/17-蒙牛六一八2.jpg",
            "images/3d/18-蒙蒙1.jpg",
            "images/3d/18-蒙蒙2.jpg",
            "images/3d/19-牛气1.jpg",
            "images/3d/19-牛气2.jpg",
            "images/3d/20-五丰1.jpg",
            "images/3d/20-五丰2.jpg"
        ]
    }
];
