const portfolioData = [
    {
        id: 1,
        title: "产品KV",
        category: "视觉设计 / Visual Design",
        cover: "https://placehold.co/600x800/0000ff/0000ff",
        date: "2025.10",
        description: "高品质产品主视觉设计，通过极简的几何构图突出核心卖点。",
        concept: "包豪斯主义构图，利用强烈的明暗对比和线性排版，引导用户视觉焦点。",
        images: [
            "images/kv/kv (1).jpg", "images/kv/kv (2).jpg", "images/kv/kv (3).jpg",
            "images/kv/kv (4).jpg", "images/kv/kv (5).jpg", "images/kv/kv (6).jpg",
            "images/kv/kv (7).jpg", "images/kv/kv (8).jpg", "images/kv/kv (9).jpg",
            "images/kv/kv (10).jpg", "images/kv/kv (11).jpg", "images/kv/kv (12).jpg",
            "images/kv/kv (13).jpg", "images/kv/kv (14).jpg", "images/kv/kv (15).jpg",
            "images/kv/kv (16).jpg", "images/kv/kv (17).jpg", "images/kv/kv (18).jpg",
            "images/kv/kv (19).jpg", "images/kv/kv (20).jpg", "images/kv/kv (21).jpg",
            "images/kv/kv (22).jpg", "images/kv/kv (23).jpg", "images/kv/kv (24).jpg",
            "images/kv/kv (25).jpg", "images/kv/kv (26).jpg", "images/kv/kv (27).jpg",
            "images/kv/kv (28).jpg", "images/kv/kv (29).jpg", "images/kv/kv (30).jpg",
            "images/kv/kv (31).jpg", "images/kv/kv (32).jpg", "images/kv/kv (33).jpg",
            "images/kv/kv (34).jpg", "images/kv/kv (35).jpg", "images/kv/kv (36).jpg",
            "images/kv/kv (37).jpg", "images/kv/kv (38).jpg", "images/kv/kv (39).jpg",
            "images/kv/kv (40).jpg", "images/kv/kv (41).jpg", "images/kv/kv (42).jpg",
            "images/kv/kv (43).jpg", "images/kv/kv (44).jpg", "images/kv/kv (45).jpg",
            "images/kv/kv (46).jpg", "images/kv/kv (47).jpg", "images/kv/kv (48).jpg",
            "images/kv/kv (49).jpg", "images/kv/kv (50).jpg", "images/kv/kv (51).jpg",
            "images/kv/kv (52).jpg", "images/kv/kv (53).jpg", "images/kv/kv (54).jpg",
            "images/kv/kv (55).jpg", "images/kv/kv (56).jpg", "images/kv/kv (57).jpg",
            "images/kv/kv (58).jpg", "images/kv/kv (59).jpg", "images/kv/kv (60).jpg",
            "images/kv/kv (61).jpg", "images/kv/kv (62).jpg", "images/kv/kv (63).jpg",
            "images/kv/kv (64).jpg", "images/kv/kv (65).jpg", "images/kv/kv (66).jpg",
            "images/kv/kv (67).jpg", "images/kv/kv (68).jpg", "images/kv/kv (69).jpg",
            "images/kv/kv (70).jpg", "images/kv/kv (71).jpg", "images/kv/kv (72).jpg",
            "images/kv/kv (73).jpg"
        ]
    },
    {
        id: 6,
        title: "动态视频",
        category: "动态图形 / Motion Graphics",
        cover: "https://placehold.co/600x800/ffffff/ffffff",
        date: "2024.10",
        description: "富有节奏感的动态视觉呈现，将平面构图与时间维度深度结合。",
        concept: "流动的包豪斯，通过关键帧的精确控制，展现几何元素的韵律之美。",
        images: [
            "images/motion/mov (1).mp4", "images/motion/mov (2).mp4", "images/motion/mov (3).mp4",
            "images/motion/mov (4).mp4", "images/motion/mov (5).mp4", "images/motion/mov (6).mp4",
            "images/motion/mov (7).mp4", "images/motion/mov (8).mp4", "images/motion/mov (9).mp4",
            "images/motion/mov (10).mp4", "images/motion/mov (11).mp4", "images/motion/mov (12).mp4",
            "images/motion/gif (1).GIF", "images/motion/gif (2).GIF", "images/motion/gif (3).GIF"
        ]
    },
    {
        id: 4,
        title: "AIGC",
        coverTitle: "聚焦AI",
        category: "实时跟随 / AI Technology",
        cover: "https://placehold.co/600x800/0000ff/0000ff",
        date: "2025.02",
        description: "利用 AI 生成技术探索视觉边界，将算法逻辑转化为包豪斯式的纯粹美感。",
        concept: "算法与美学的交汇，通过人工干预使 AI 产出具备严谨的几何秩序。",
        images: [
            "images/aigc/ai (1).jpeg", "images/aigc/ai (1).png", "images/aigc/ai (2).jpeg",
            "images/aigc/ai (2).png", "images/aigc/ai (3).png", "images/aigc/ai (4).png",
            "images/aigc/ai (5).png", "images/aigc/ai (6).png", "images/aigc/ai (7).png",
            "images/aigc/ai (8).png", "images/aigc/ai (9).png", "images/aigc/ai (10).png",
            "images/aigc/ai (11).png", "images/aigc/ai (12).png", "images/aigc/ai (13).png",
            "images/aigc/ai (14).png", "images/aigc/ai (15).png", "images/aigc/ai (16).png",
            "images/aigc/ai (17).png", "images/aigc/ai (18).png", "images/aigc/ai (19).png",
            "images/aigc/ai (20).png", "images/aigc/ai (21).png", "images/aigc/ai (22).png",
            "images/aigc/ai (23).png", "images/aigc/ai (24).png", "images/aigc/ai (25).png",
            "images/aigc/ai (26).png"
        ]
    },
    {
        id: 5,
        title: "产品建模",
        category: "3D建模 / 3D Modeling",
        cover: "https://placehold.co/600x800/ffffff/ffffff",
        date: "2024.12",
        description: "高精度 3D 产品建模，还原工业设计的材质质感与纯粹结构。",
        concept: "在三维空间中重塑几何基本型，探索光影在纯净表面的自然流动。",
        images: [
            "images/3d/3d1 (1).jpeg", "images/3d/3d1 (1).png",
            "images/3d/3d1 (2).jpeg", "images/3d/3d1 (2).png",
            "images/3d/3d1 (3).png", "images/3d/3d1 (4).png",
            "images/3d/3d1 (5).png", "images/3d/3d1 (6).png"
        ]
    },
    {
        id: 2,
        title: "产品详情",
        category: "交互设计 / Interaction Design",
        cover: "https://placehold.co/600x800/0000ff/0000ff",
        date: "2025.08",
        description: "深度的产品细节展示，结合信息图表和极简排版，清晰传达产品参数。",
        concept: "形式追随功能。每一个视觉元素都是为了更高效的信息传递。",
        images: [
            "images/detail/detail (1).jpeg", "images/detail/detail (1).jpg", "images/detail/detail (1).png",
            "images/detail/detail (2).jpeg", "images/detail/detail (2).png",
            "images/detail/detail (3).jpeg", "images/detail/detail (3).png",
            "images/detail/detail (4).jpeg", "images/detail/detail (4).png",
            "images/detail/detail (5).jpeg", "images/detail/detail (5).png",
            "images/detail/detail (6).jpeg", "images/detail/detail (6).png",
            "images/detail/detail (7).jpeg", "images/detail/detail (7).png",
            "images/detail/detail (8).jpeg", "images/detail/detail (8).png",
            "images/detail/detail (9).jpeg", "images/detail/detail (9).png",
            "images/detail/detail (10).jpeg", "images/detail/detail (10).png",
            "images/detail/detail (11).jpeg", "images/detail/detail (11).png",
            "images/detail/detail (12).jpeg", "images/detail/detail (12).png",
            "images/detail/detail (13).jpeg", "images/detail/detail (13).png",
            "images/detail/detail (14).jpeg", "images/detail/detail (14).png",
            "images/detail/detail (15).jpeg", "images/detail/detail (15).png",
            "images/detail/detail (16).jpeg", "images/detail/detail (16).png",
            "images/detail/detail (17).jpeg", "images/detail/detail (17).png",
            "images/detail/detail (18).jpeg", "images/detail/detail (18).png",
            "images/detail/detail (19).jpeg", "images/detail/detail (19).png",
            "images/detail/detail (20).jpeg", "images/detail/detail (20).png",
            "images/detail/detail (21).jpeg", "images/detail/detail (21).png",
            "images/detail/detail (22).jpeg", "images/detail/detail (22).png",
            "images/detail/detail (23).jpeg", "images/detail/detail (23).png",
            "images/detail/detail (24).jpeg", "images/detail/detail (24).png",
            "images/detail/detail (25).jpeg", "images/detail/detail (25).png",
            "images/detail/detail (26).jpeg", "images/detail/detail (26).png",
            "images/detail/detail (27).jpeg", "images/detail/detail (27).png",
            "images/detail/detail (28).jpeg", "images/detail/detail (28).png",
            "images/detail/detail (29).jpeg", "images/detail/detail (29).png",
            "images/detail/detail (30).png", "images/detail/detail (31).png",
            "images/detail/detail (32).png", "images/detail/detail (33).png",
            "images/detail/detail (34).png", "images/detail/detail (35).png",
            "images/detail/detail (36).png", "images/detail/detail (37).png",
            "images/detail/detail (38).png", "images/detail/detail (39).png",
            "images/detail/detail (40).png", "images/detail/detail (41).png",
            "images/detail/detail (42).png", "images/detail/detail (43).png",
            "images/detail/detail (44).png", "images/detail/detail (45).png",
            "images/detail/detail (46).png", "images/detail/detail (47).png",
            "images/detail/detail (48).png"
        ]
    },
    {
        id: 3,
        title: "完整页面",
        category: "网页设计 / Web Design",
        cover: "https://placehold.co/600x800/ffffff/ffffff",
        date: "2025.05",
        description: "全站式极简网页布局，采用规整的网格系统，提供流畅的响应式体验。",
        concept: "现代包豪斯数字实践，打破传统束缚，追求空间与节奏的完美平衡。",
        images: [
            "images/web/web (1).jpg", "images/web/web (1).png", "images/web/web (1).jpeg",
            "images/web/web (2).jpg", "images/web/web (2).png", "images/web/web (2).jpeg",
            "images/web/web (3).jpg", "images/web/web (3).png", "images/web/web (3).jpeg",
            "images/web/web (4).jpg", "images/web/web (4).png", "images/web/web (4).jpeg",
            "images/web/web (5).jpg", "images/web/web (5).png", "images/web/web (5).jpeg",
            "images/web/web (6).png", "images/web/web (6).jpeg",
            "images/web/web (7).png", "images/web/web (7).jpeg",
            "images/web/web (8).png", "images/web/web (8).jpeg",
            "images/web/web (9).png", "images/web/web (9).jpeg",
            "images/web/web (10).png", "images/web/web (10).jpeg",
            "images/web/web (11).png", "images/web/web (11).jpeg",
            "images/web/web (12).png", "images/web/web (12).jpeg",
            "images/web/web (13).png", "images/web/web (13).jpeg",
            "images/web/web (14).png", "images/web/web (14).jpeg",
            "images/web/web (15).png", "images/web/web (15).jpeg",
            "images/web/web (16).png", "images/web/web (16).jpeg",
            "images/web/web (17).png", "images/web/web (17).jpeg",
            "images/web/web (18).png", "images/web/web (18).jpeg",
            "images/web/web (19).png", "images/web/web (19).jpeg",
            "images/web/web (20).png", "images/web/web (20).jpeg",
            "images/web/web (21).png", "images/web/web (21).jpeg",
            "images/web/web (22).png", "images/web/web (22).jpeg",
            "images/web/web (23).png", "images/web/web (23).jpeg",
            "images/web/web (24).png", "images/web/web (24).jpeg",
            "images/web/web (25).png", "images/web/web (25).jpeg",
            "images/web/web (26).png", "images/web/web (27).png",
            "images/web/web (28).png", "images/web/web (29).png", "images/web/web (30).png"
        ]
    },
    {
        id: 999,
        title: "全部作品",
        category: "作品集总览 / All Works",
        cover: "", // Not used
        date: "2024-2025",
        description: "这里汇集了所有的设计探索与实践成果。",
        concept: "从平面到动态，从二维到三维，全方位的视觉呈现。",
        images: [
            // 产品KV (最高权限)
            "images/kv/kv (1).jpg", "images/kv/kv (2).jpg", "images/kv/kv (3).jpg",
            "images/kv/kv (4).jpg", "images/kv/kv (5).jpg", "images/kv/kv (6).jpg",
            "images/kv/kv (7).jpg", "images/kv/kv (8).jpg", "images/kv/kv (9).jpg",
            "images/kv/kv (10).jpg", "images/kv/kv (11).jpg", "images/kv/kv (12).jpg",
            "images/kv/kv (13).jpg", "images/kv/kv (14).jpg", "images/kv/kv (15).jpg",
            "images/kv/kv (16).jpg", "images/kv/kv (17).jpg", "images/kv/kv (18).jpg",
            "images/kv/kv (19).jpg", "images/kv/kv (20).jpg", "images/kv/kv (21).jpg",
            "images/kv/kv (22).jpg", "images/kv/kv (23).jpg", "images/kv/kv (24).jpg",
            "images/kv/kv (25).jpg", "images/kv/kv (26).jpg", "images/kv/kv (27).jpg",
            "images/kv/kv (28).jpg", "images/kv/kv (29).jpg", "images/kv/kv (30).jpg",
            "images/kv/kv (31).jpg", "images/kv/kv (32).jpg", "images/kv/kv (33).jpg",
            "images/kv/kv (34).jpg", "images/kv/kv (35).jpg", "images/kv/kv (36).jpg",
            "images/kv/kv (37).jpg", "images/kv/kv (38).jpg", "images/kv/kv (39).jpg",
            "images/kv/kv (40).jpg", "images/kv/kv (41).jpg", "images/kv/kv (42).jpg",
            "images/kv/kv (43).jpg", "images/kv/kv (44).jpg", "images/kv/kv (45).jpg",
            "images/kv/kv (46).jpg", "images/kv/kv (47).jpg", "images/kv/kv (48).jpg",
            "images/kv/kv (49).jpg", "images/kv/kv (50).jpg", "images/kv/kv (51).jpg",
            "images/kv/kv (52).jpg", "images/kv/kv (53).jpg", "images/kv/kv (54).jpg",
            "images/kv/kv (55).jpg", "images/kv/kv (56).jpg", "images/kv/kv (57).jpg",
            "images/kv/kv (58).jpg", "images/kv/kv (59).jpg", "images/kv/kv (60).jpg",
            "images/kv/kv (61).jpg", "images/kv/kv (62).jpg", "images/kv/kv (63).jpg",
            "images/kv/kv (64).jpg", "images/kv/kv (65).jpg", "images/kv/kv (66).jpg",
            "images/kv/kv (67).jpg", "images/kv/kv (68).jpg", "images/kv/kv (69).jpg",
            "images/kv/kv (70).jpg", "images/kv/kv (71).jpg", "images/kv/kv (72).jpg",
            "images/kv/kv (73).jpg",
            
            // 动态视频
            "images/motion/mov (1).mp4", "images/motion/mov (2).mp4", "images/motion/mov (3).mp4",
            "images/motion/mov (4).mp4", "images/motion/mov (5).mp4", "images/motion/mov (6).mp4",
            "images/motion/mov (7).mp4", "images/motion/mov (8).mp4", "images/motion/mov (9).mp4",
            "images/motion/mov (10).mp4", "images/motion/mov (11).mp4", "images/motion/mov (12).mp4",
            "images/motion/gif (1).GIF", "images/motion/gif (2).GIF", "images/motion/gif (3).GIF",
            
            // 聚焦AI
            "images/aigc/ai (1).jpeg", "images/aigc/ai (1).png", "images/aigc/ai (2).jpeg",
            "images/aigc/ai (2).png", "images/aigc/ai (3).png", "images/aigc/ai (4).png",
            "images/aigc/ai (5).png", "images/aigc/ai (6).png", "images/aigc/ai (7).png",
            "images/aigc/ai (8).png", "images/aigc/ai (9).png", "images/aigc/ai (10).png",
            "images/aigc/ai (11).png", "images/aigc/ai (12).png", "images/aigc/ai (13).png",
            "images/aigc/ai (14).png", "images/aigc/ai (15).png", "images/aigc/ai (16).png",
            "images/aigc/ai (17).png", "images/aigc/ai (18).png", "images/aigc/ai (19).png",
            "images/aigc/ai (20).png", "images/aigc/ai (21).png", "images/aigc/ai (22).png",
            "images/aigc/ai (23).png", "images/aigc/ai (24).png", "images/aigc/ai (25).png",
            "images/aigc/ai (26).png",
            
            // 完整页面
            "images/web/web (1).jpg", "images/web/web (1).png", "images/web/web (1).jpeg",
            "images/web/web (2).jpg", "images/web/web (2).png", "images/web/web (2).jpeg",
            "images/web/web (3).jpg", "images/web/web (3).png", "images/web/web (3).jpeg",
            "images/web/web (4).jpg", "images/web/web (4).png", "images/web/web (4).jpeg",
            "images/web/web (5).jpg", "images/web/web (5).png", "images/web/web (5).jpeg",
            "images/web/web (6).png", "images/web/web (6).jpeg",
            "images/web/web (7).png", "images/web/web (7).jpeg",
            "images/web/web (8).png", "images/web/web (8).jpeg",
            "images/web/web (9).png", "images/web/web (9).jpeg",
            "images/web/web (10).png", "images/web/web (10).jpeg",
            "images/web/web (11).png", "images/web/web (11).jpeg",
            "images/web/web (12).png", "images/web/web (12).jpeg",
            "images/web/web (13).png", "images/web/web (13).jpeg",
            "images/web/web (14).png", "images/web/web (14).jpeg",
            "images/web/web (15).png", "images/web/web (15).jpeg",
            "images/web/web (16).png", "images/web/web (16).jpeg",
            "images/web/web (17).png", "images/web/web (17).jpeg",
            "images/web/web (18).png", "images/web/web (18).jpeg",
            "images/web/web (19).png", "images/web/web (19).jpeg",
            "images/web/web (20).png", "images/web/web (20).jpeg",
            "images/web/web (21).png", "images/web/web (21).jpeg",
            "images/web/web (22).png", "images/web/web (22).jpeg",
            "images/web/web (23).png", "images/web/web (23).jpeg",
            "images/web/web (24).png", "images/web/web (24).jpeg",
            "images/web/web (25).png", "images/web/web (25).jpeg",
            "images/web/web (26).png", "images/web/web (27).png",
            "images/web/web (28).png", "images/web/web (29).png", "images/web/web (30).png",
            
            // 产品详情
            "images/detail/detail (1).jpeg", "images/detail/detail (1).jpg", "images/detail/detail (1).png",
            "images/detail/detail (2).jpeg", "images/detail/detail (2).png",
            "images/detail/detail (3).jpeg", "images/detail/detail (3).png",
            "images/detail/detail (4).jpeg", "images/detail/detail (4).png",
            "images/detail/detail (5).jpeg", "images/detail/detail (5).png",
            "images/detail/detail (6).jpeg", "images/detail/detail (6).png",
            "images/detail/detail (7).jpeg", "images/detail/detail (7).png",
            "images/detail/detail (8).jpeg", "images/detail/detail (8).png",
            "images/detail/detail (9).jpeg", "images/detail/detail (9).png",
            "images/detail/detail (10).jpeg", "images/detail/detail (10).png",
            "images/detail/detail (11).jpeg", "images/detail/detail (11).png",
            "images/detail/detail (12).jpeg", "images/detail/detail (12).png",
            "images/detail/detail (13).jpeg", "images/detail/detail (13).png",
            "images/detail/detail (14).jpeg", "images/detail/detail (14).png",
            "images/detail/detail (15).jpeg", "images/detail/detail (15).png",
            "images/detail/detail (16).jpeg", "images/detail/detail (16).png",
            "images/detail/detail (17).jpeg", "images/detail/detail (17).png",
            "images/detail/detail (18).jpeg", "images/detail/detail (18).png",
            "images/detail/detail (19).jpeg", "images/detail/detail (19).png",
            "images/detail/detail (20).jpeg", "images/detail/detail (20).png",
            "images/detail/detail (21).jpeg", "images/detail/detail (21).png",
            "images/detail/detail (22).jpeg", "images/detail/detail (22).png",
            "images/detail/detail (23).jpeg", "images/detail/detail (23).png",
            "images/detail/detail (24).jpeg", "images/detail/detail (24).png",
            "images/detail/detail (25).jpeg", "images/detail/detail (25).png",
            "images/detail/detail (26).jpeg", "images/detail/detail (26).png",
            "images/detail/detail (27).jpeg", "images/detail/detail (27).png",
            "images/detail/detail (28).jpeg", "images/detail/detail (28).png",
            "images/detail/detail (29).jpeg", "images/detail/detail (29).png",
            "images/detail/detail (30).png", "images/detail/detail (31).png",
            "images/detail/detail (32).png", "images/detail/detail (33).png",
            "images/detail/detail (34).png", "images/detail/detail (35).png",
            "images/detail/detail (36).png", "images/detail/detail (37).png",
            "images/detail/detail (38).png", "images/detail/detail (39).png",
            "images/detail/detail (40).png", "images/detail/detail (41).png",
            "images/detail/detail (42).png", "images/detail/detail (43).png",
            "images/detail/detail (44).png", "images/detail/detail (45).png",
            "images/detail/detail (46).png", "images/detail/detail (47).png",
            "images/detail/detail (48).png"
        ]
    }
];